### ISSUE TITLE
For sample loop...

### ISSUE THREAD

**Issue by JulesOLVERA** [alexpreynolds/sample#5]
Hi Alex, hope you're fine.

I hope you can give me some light (I am a beginner in the bioinformatics field and I am stuck in an analysis step). I have some fastq files that I need to downsample and I wanted to use sample for it. I was trying to do a for loop in bash. My fastq files have the format:

xxYYY_R1_paired.fastq.gz   &   xxYYY_R2_paired.fastq.gz (forward & revers paired-ends respectively), where xx is an individual number and YYY the population where the sample came from. 

The loop I tried is: 
for i in `ls *_paired.fastq.gz` ; do echo sample -k 10000000 -l 4 -s 1000 $i > sub$i ; done
but the command only gives semi-empty files (57 octets size) which do not appear to be gz or fastq files (FastQC programme does not recognize the format and does not open the files). 

Do you know what could be wrong with the command ? Have you any advice to loop sample for many paired-end fastq files ? 

Thanks in advance and continue to have a nice week,

Julián OLVERA

**Comment by alexpreynolds** [comment]
Hello Julián,

It is not possible to directly sample compressed files. What you could do, however, is extract the files temporarily, sample, and then delete the extracted files:

```
for biosample_fn in `ls *_paired.fastq.gz`
do 
    biosample_extracted_fn="/tmp/${biosample_fn##*/}.fq"
    gunzip -c "${biosample_fn}" > "${biosample_extracted_fn}"
    biosample_sample_fn="${biosample_fn##*/}.sample.gz"
    sample -k 10000000 -l 4 -d 1234 -s "${biosample_extracted_fn}" | gzip -c > "${biosample_sample_fn}"
    rm "${biosample_extracted_fn}"
done
```

Note that I'm changing the options slightly, so that you are using the same [random seed](https://en.wikipedia.org/wiki/Random_seed?useskin=vector) for every sample you take. 

Using the same random seed will generate the same sequence of random lines. This would be important for paired-end reads, because you want to get the same pairs of reads from each pairing. 

I'm picking `1234` here, but for a representative random sampling, you probably want to change this up for each pair of paired-end reads. 

In other words, for individual `xx` and population `YYY`, you have reads `R1` and `R2`. You would pick a unique random seed specific to this pairing. For the next pair of reads, you would use a different random seed.

The following line uses the [basename](https://stackoverflow.com/a/2664746/19410) of `biosample_fn` to store the extracted file in `/tmp`:

```
biosample_extracted_fn="/tmp/${biosample_fn##*/}.fq"
```

You are specifying a `k` of 10M, which is pretty large, so it might be a good idea to compress the random sample. The following line stores the sample as a compressed file in the current working directory:

```
biosample_sample_fn="${biosample_fn##*/}.sample.gz"
```

If you need to put results in another directory, you could edit the above file to put a directory before the variable:

```
biosample_sample_fn="/some/results/directory/${biosample_fn##*/}.sample.gz"
```

I hope this helps you get started.
